#!/bin/bash -e

ARCHS="x86_64 i386"
BIGCOUCH_TAG="0.4.0"
BIGCOUCH_VERSION="0.4.0"
ERLANG_VERSION="otp_src_R14B01"
MIRROR="http://mirrors.kernel.org/centos"

# Install dependencies
sudo apt-get install -y rpm yum

build() {
    DIR=~/rpm/centos-$1-$2
    mkdir -p $DIR

    if [ "$2" == "i386" ]; then SETARCH="linux32"; else SETARCH="linux64"; fi

    if [ ! -f "$DIR/.finished" ];
    then
        mkdir -p $DIR/etc
        sudo cp /etc/resolv.conf $DIR/etc/
        cat <<EOF | sudo tee $DIR/etc/yum.conf > /dev/null
[main]
distroverpkg=centos-release
gpgcheck=0
multilib_policy=best
EOF
        $SETARCH rpm --rebuilddb --root=$DIR
        wget -c "$MIRROR/$4/$3"
        $SETARCH sudo rpm -i --nodeps --replacepkgs --root $DIR $3
        $SETARCH sudo yum \
            --installroot $DIR \
            --nogpgcheck install -y \
            tar rpm-build yum
        sudo touch "$DIR/.finished"
    fi

    # Setup bind mounts
    sudo mount --bind /proc $DIR/proc
    sudo mount --bind /dev $DIR/dev
    trap "sudo umount $DIR/proc; sudo umount $DIR/dev" EXIT

    $SETARCH sudo chroot $DIR \
        yum install -y tar rpm-build

    # Setup
    sudo mkdir -p $DIR$HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    cat <<EOF | sudo tee $DIR$HOME/.rpmmacros > /dev/null
%_topdir %(echo $HOME)/rpmbuild
EOF
    sudo mkdir -p ~/rpm/centos-$1-$2_result

    # Build SpiderMonkey package (only on CentOS 6)
    if [ "$1" = "6" -a -z "$(find ${DIR}_result -maxdepth 1 -name 'js-*.rpm' -print -quit)" ];
    then
        $SETARCH sudo chroot $DIR yum install -y \
            autoconf213 gcc gcc-c++ make nspr-devel \
            python zip readline-devel ncurses-devel rpmlib \
            pkgconfig

        sudo cp js.spec $DIR$HOME
        sudo cp js*.patch js*.tar.gz $DIR$HOME/rpmbuild/SOURCES
        $SETARCH sudo chroot $DIR rpmbuild -ba $HOME/js.spec
        $SETARCH sudo chroot $DIR rpm --install --force --nodeps $HOME/rpmbuild/RPMS/$2/*.rpm
        sudo cp $DIR$HOME/rpmbuild/RPMS/$2/*.rpm ~/rpm/centos-$1-$2_result/
    fi

    # Install js-devel (only on CentOS 5)
    if [ "$1" = "5" -a -z "$(find ${DIR}_result -maxdepth 1 -name 'js-*.rpm' -print -quit)" ];
    then
        EPEL_PATH="http://download.fedoraproject.org/pub/epel/$1/i386"
        if [ "$1" == "5" ];
        then
            EPEL_NAME="epel-release-5-4.noarch.rpm"
        elif [ "$1" == "6" ];
        then
            EPEL_NAME="epel-release-6-5.noarch.rpm"
        else
            echo "No EPEL found for $1"
            exit
        fi
        wget -c $EPEL_PATH/$EPEL_NAME
        $SETARCH sudo rpm --install --force --root=$DIR $EPEL_NAME
        $SETARCH sudo chroot $DIR yum install -y js-devel
    fi

    # Install erlang
    if test -z "$(find $DIR/usr/local/bin -maxdepth 1 -name 'erl' -print -quit)"
    then
        $SETARCH sudo chroot $DIR yum install -y \
            make gcc gcc-c++ kernel-devel m4 ncurses-devel openssl-devel java-1.6.0-openjdk-devel \
            python libicu-devel openssl-devel curl-devel git

        sudo cp $ERLANG_VERSION.tar.gz $DIR$HOME
        cat <<EOF > build_erlang
#!/bin/bash -e
cd ~
tar zxf $ERLANG_VERSION.tar.gz
cd $ERLANG_VERSION
./configure \
    --enable-kernel-poll \
    --enable-hipe \
    --enable-threads \
    --enable-smp-support
make
make install
EOF
        chmod +x build_erlang
        sudo cp build_erlang $DIR$HOME
        $SETARCH sudo chroot $DIR ~/build_erlang
    fi

    # Build BigCouch package
    if test -z "$(find ${DIR}_result -maxdepth 1 -name 'bigcouch-*.rpm' -print -quit)"
    then
        sudo cp -f bigcouch.spec $DIR$HOME/
        sudo cp -f bigcouch.tar.gz $DIR$HOME/rpmbuild/SOURCES/
        $SETARCH sudo GIT_SSL_NO_VERIFY=1 chroot $DIR rpmbuild -ba $HOME/bigcouch.spec \
            --define "_revision $BIGCOUCH_VERSION" --define "_release 1"
    fi

    # Extract RPM's
    sudo cp $DIR$HOME/rpmbuild/RPMS/$2/*.rpm ~/rpm/centos-$1-$2_result/

    # Remove bind mounts
    sudo umount $DIR/proc
    sudo umount $DIR/dev

    # Clean up
    sudo rm -rf $DIR

    trap - EXIT
}

js_src() {
    JS="js-1.8.5"
    wget -c http://infrastructure.fedoraproject.org/repo/pub/fedora/linux/releases/16/Fedora/source/SRPMS/$JS-7.fc16.src.rpm
    mkdir -p $JS
    rpm2cpio $JS*.src.rpm | cpio -i
}

bigcouch_src() {
    rm -rf bigcouch
    git clone git://github.com/cloudant/bigcouch.git
    pushd bigcouch
    git remote add couchdb http://git-wip-us.apache.org/repos/asf/couchdb.git
    git checkout $BIGCOUCH_TAG
    popd
    tar czf bigcouch.tar.gz bigcouch
}

erlang_src() {
    wget -c http://erlang.org/download/$ERLANG_VERSION.tar.gz
}

js_src
bigcouch_src
erlang_src

# Build all the things
build "6" "x86_64" "centos-release-6-2.el6.centos.7.x86_64.rpm" "6/os/x86_64/Packages"
build "6" "i386" "centos-release-6-2.el6.centos.7.i686.rpm" "6/os/i386/Packages"

build "5" "x86_64" "centos-release-5-7.el5.centos.x86_64.rpm" "5/os/x86_64/CentOS"
build "5" "i386" "centos-release-5-7.el5.centos.i386.rpm" "5/os/i386/CentOS"
