#!/bin/sh -e

if [ -x "/usr/local/bin/erl" ];
then
    echo "Erlang already built."
    exit 0
fi

HOME=/tmp/
export http_proxy="http://localhost:8123"
erlang_version="otp_src_R14B01"
erlang_options="--enable-kernel-poll --enable-hipe --enable-threads --enable-smp-support"

apt-get -y install gcc g++ wget build-essential autoconf libncurses-dev openjdk-6-jdk libssl-dev
echo -n "Fetching erlang tarball: "
wget --quiet -c http://erlang.org/download/$erlang_version.tar.gz
echo "done"
tar zxf $erlang_version.tar.gz
cd $erlang_version

./configure $erlang_options
make
make install

ln -s /usr/local/bin/erl /usr/bin/erl
ln -s /usr/local/bin/erlc /usr/bin/erlc
ln -s /usr/local/bin/escript /usr/bin/escript

# Cleanup
rm -f $erlang_version.tar.gz
rm -rf $erlang_version
